name: tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
        id: go

      - name: Install environments
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.57.2
          sudo cp bin/golangci-lint /usr/local/bin/golangci-lint
          go install github.com/klmitch/overcover@latest
          go install github.com/qor/bindatafs@latest
          npm install -g codeclimate-test-reporter

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: |
          export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"
          export PATH=$PATH:$(go env GOPATH)/bin
          make testallv
          codeclimate-test-reporter < coverage.out
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECLIMATE_API_HOST: https://codebeat.co/webhooks/code_coverage
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}